### ISSUE TITLE
In c3sl2_delivery_v1, several files for the same site, at the same date

### ISSUE THREAD

**Issue by floriankrb** [floriankrb/mf-bugtracking#1]
In c3sl2_delivery_v1, I see several files for the same site, at the same date. 

`ls 20020102/*Tuz_Golu*                                                                                                                                                                   `
20020102/c3s_L2B_20020102_Tuz_Golu_104_1KM_VGT_V1.0.1.nc  20020102/c3s_L2B_20020102_Tuz_Golu_2_104_1KM_VGT_V1.0.1.nc  20020102/c3s_L2B_20020102_Tuz_Golu_3_104_1KM_VGT_V1.0.1.nc
20020102/c3s_L2B_20020102_Tuz_Golu_105_1KM_VGT_V1.0.1.nc  20020102/c3s_L2B_20020102_Tuz_Golu_2_105_1KM_VGT_V1.0.1.nc  20020102/c3s_L2B_20020102_Tuz_Golu_3_105_1KM_VGT_V1.0.1.nc

Is it expected ? Can you clarify ? What is 104 and 105 in the filename ?

Their attribute  'time_coverage_start' :
2002/01/02 07:50:20 input-data/20020102/c3s_L2B_20020102_Tuz_Golu_104_1KM_VGT_V1.0.1.nc
2002/01/02 09:31:47 input-data/20020102/c3s_L2B_20020102_Tuz_Golu_105_1KM_VGT_V1.0.1.nc
2002/01/02 07:50:20 input-data/20020102/c3s_L2B_20020102_Tuz_Golu_2_104_1KM_VGT_V1.0.1.nc
2002/01/02 09:31:47 input-data/20020102/c3s_L2B_20020102_Tuz_Golu_2_105_1KM_VGT_V1.0.1.nc
2002/01/02 07:50:20 input-data/20020102/c3s_L2B_20020102_Tuz_Golu_3_104_1KM_VGT_V1.0.1.nc
2002/01/02 09:31:47 input-data/20020102/c3s_L2B_20020102_Tuz_Golu_3_105_1KM_VGT_V1.0.1.nc
does not help me to understand what is happening.

Attached is the TOC picture for these files.
![figure_5-1](https://user-images.githubusercontent.com/8441217/38559323-022ecc7c-3cd3-11e8-8892-baa73b11ca9c.png)

**Comment by iskandervito** [comment]
Florian,
The numbers 104 and 105 are the segment number. An aeronet  site can be covered by multiple segments (orbit). so this is a  normal and expected. In general aeronet sites with latitude higher than 35° and lower than 35° could be observed at least twice a day. You can take an aeronet around the equator and you will never see that this site is observed twice.
Iskander

**Comment by floriankrb** [comment]
Great ! thanks !

**Comment by floriankrb** [comment]
What about these ones ?
20021222/c3s_L2B_20021222_Kyiv_088_1KM_VGT_V1.0.1.nc 
20021222/c3s_L2B_20021222_Kyiv-AO_088_1KM_VGT_V1.0.1.nc

and 
20021222/c3s_L2B_20021222_Karlsruhe_089_1KM_VGT_V1.0.1.nc  20021222/c3s_L2B_20021222_KITcube_Karlsruhe_089_1KM_VGT_V1.0.1.nc
 and
20021222/c3s_L2B_20021222_Bucarest_088_1KM_VGT_V1.0.1.nc  20021222/c3s_L2B_20021222_Bucharest_Inoe_088_1KM_VGT_V1.0.1.nc

Are they the same site ? 
Should I rely on the filename to indentify the site, or should I look at the latitudes and longitudes in each files ?

**Comment by iskandervito** [comment]
We used a list of aeronet site with corresponding names (so if names are different, it means different sites/location). Looking at the coordinates of these site (see below), they have different lon/lat coordinates so our processing generates then both sites. 
Kyiv,30.496667,50.363611,200.000000
Kyiv-AO,30.498000,50.452300,200.000000
 
You should rely on the file name  and do a batch processing on each site

**Comment by floriankrb** [comment]
Ok.

And the site names are the one from `https://aeronet.gsfc.nasa.gov/cgi-bin/draw_map_display_aod_v3?long1=-180&long2=180&lat1=-90&lat2=90&multiplier=2&what_map=4&nachal=1&formatter=0&level=3&place_code=10&place_limit=0` 
And we filtered out to keep only the ones on the MSG disk to make latter comparison easier.

As for the duplicates, they are not duplicates, the lat/lon are different when the name is different. For instance, there are three sites aound Toulouse : 
Toulouse,43.575,1.374
TOULOUSE,43.562,1.476
Toulouse_MF,43.573,1.374
There location is different and the dates where the data is available is different too (even if we could merge them at the end for visualisation).
